import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json'
import { initialCheckout } from '../lib/payment'

const defaultCart = {
  products: {}
}
export default function Home() {
  const [cart, setCart] = useState(defaultCart)

  const cartItems = Object.keys(cart.products).map(key=>{
    const product = products.find(({id})=>`${id}` ===`${key}`)
    return{
      ...cart.products[key],
      pricePerItem:product.price
    }
  })

  const subTotal = cartItems.reduce((acc,{pricePerItem,quantity})=>{
    return acc + (pricePerItem*quantity)
  },0)

  const totalItem = cartItems.reduce((acc,{quantity})=>{
    return acc + quantity
  },0)

  console.log(subTotal,'total');

  const addToCart = (product) => {
    const {id} = product
    const cartState ={ ...cart}
    if(cartState.products[id]){
      console.log('already in');
      cartState.products[id].quantity = cartState.products[id].quantity + 1
    }else{
        cartState.products[id] = {
          id,
          name:product.title,
          quantity: 1
        }  
    }
    setCart(cartState)


    // setCart(prev => {
    //   let cartState = { ...cart }

    //   if (cartState.products[id]) {
    //     cartState.products[id].quantity = cartState.products[id].quantity + 1
    //   } else {
    //     cartState.products[id] = {
    //       id,
    //       name:product.title,
    //       quantity: 1
    //     }
    //   }
    //   return cartState
    // })
  }
console.log(cart);

const checkout =() =>{
  initialCheckout({ lineItems: cartItems.map((item)=>{
    return{
      price:item.id,
      quantity:item.quantity
    }
  }) })
}

  return (
    <div className={styles.container}>
      <Head>
        <title>shopppp</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the best shop dude</h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <p className={styles.description}>
          <strong> Items:</strong> {totalItem}
          <br />
          <strong>total: </strong> {subTotal}
          <br />
          <button className={styles.btn} onClick={checkout}>check out</button>
        </p>

        <ul className={styles.grid}>
          {products.map((product) => (
            <li className={styles.card} key={product.id}>
              <a href='https://nextjs.org/docs'>
                <img src={product.image} alt='' />
                <h2>{product.title}</h2>
                <p>{product.price} $</p>
                <p>{product.description}</p>
              </a>
              <p>
                <button
                  className={styles.btn}
                  onClick={()=>addToCart(product)}
                >
                  add it
                </button>
              </p>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
